[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node microservices/review-service/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
REVIEW_SERVICE_PORT = "10000" 